version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  # Install dependencies
  jobs:
    pre_build:
      - pip install mkdocs mkdocstrings mkdocstrings-python
      # - pip install mkdocs-theme-readthedocs

mkdocs:
  configuration: mkdocs.yml
