site_name: EZRegex Docs
use_directory_urls: false
theme: readthedocs

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
  - gen-files:
      scripts:
        - generate_docs.py
