psuedonyms = {
    'repeat': ('matchMax', 'match_max'),
    'at_most': ('matchAtMost', 'atMost', 'match_at_most',),
    'amt': ('matchNum', 'matchAmt', 'match_amt', 'match_num', 'num',),
    'between': ('matchRange', 'match_range'),
    'more_than': ('matchMoreThan', 'match_greater_than', 'matchGreaterThan', 'moreThan', 'match_more_than',),
    'at_least': ('matchAtLeast', 'match_min', 'matchMin', 'atLeast', 'match_at_least',),
    'line_starts_with': ('lineStartsWith', 'line_start', 'lineStart',),
    'string_starts_with': ('stringStartsWith', 'string_start', 'stringStart',),
    'line_ends_with': ('lineEndsWith', 'line_end', 'lineEnd',),
    'string_ends_with': ('stringEndsWith', 'string_end', 'stringEnd',),
    'chunk': ('stuff',),
    'whitechunk': ('whiteChunk', 'white'),
    'anything': ('anychar', 'anyChar', 'char'),
    'letter': ('alpha',),
    'alpha_num': ('alphanum'  , 'alpha_num',),
    'any_between': ('anyBetween',),
    'word_char': ('wordChar',),
    'hex_digit': ('hexDigit', 'hex',),
    'oct_digit': ('octDigit',),
    'new_line': ('newline', 'newLine',),
    'space_or_tab': ('spaceOrTab',),
    'carriage_return': ('carriageReturn',),
    'vertical_tab': ('verticalTab',),
    'form_feed': ('formFeed',),
    'period': ('dot',),
    'int_or_float': ('intOrFloat',),
    'not_whitespace': ('notWhitespace',),
    'not_digit': ('notDigit',),
    'not_word': ('notWord',),
    'any_of': ('anyof', 'any_of', 'anyOf', 'oneOf', 'one_of',),
    'any_except': ('anyExcept',),
    'any_char_except': ('anyCharExcept',),
    'printable_and_space': ('printableAndSpace',),
    'if_proceded_by': ('ifFollowedBy', 'if_followed_by', 'ifProcededBy',),
    'if_exists': ('ifExists',),
    'if_not_proceded_by': ('ifNotFollowedBy', 'if_not_followed_by', 'ifNotProcededBy'),
    'if_preceded_by': ('ifPrecededBy',),
    'if_not_preceded_by': ('ifNotPrecededBy',),
    'if_enclosed_with': ('ifEnclosedWith', 'if_enclosed_by', 'ifEnclosedBy',),
    'passive_group': ('passiveGroup',),
    'earlier_group': ('sameAs', 'same_as', 'earlierGroup', 'sameAsGroup', 'same_as_group',),
    'is_exactly': ('exactly', 'isExactly',),
    'optional': ('oneOrNone', 'one_or_none', 'opt',),
    'at_least_one': ('oneOrMore', 'one_or_more', 'atLeastOne', 'atLeast1', 'at_least_1',),
    'at_least_none': ('noneOrMore', 'none_or_more', 'atLeastNone', 'at_least_0', 'atLeast0', 'anyAmt', 'any_amt', 'zeroOrMore', 'zero_or_more',),
    'signed': ('integer',),
    'literally_anything': ('literallyAnything',),
    'word_boundary': ('wordBoundary',),
    'not_word_boundary': ('notWordBoundary',),
    'rgroup': ('replaceGroup', 'replace_group',),
    'replace_entire': ('replaceAll', 'replace_all', 'replaceEntire',),
}
